### ISSUE TITLE
NPM start error

### ISSUE THREAD

**Issue by claudio4** [chrisvfritz/vue-render-performance-comparisons#4]
When I run npm start command it return me a error.

I using ArchLinux x64.

Here is the [npm-debug.log](https://github.com/chrisvfritz/vue-render-performance-comparisons/files/504375/npm-debug.txt).

Thanks for your time.

**Comment by chrisvfritz** [comment]
This could be due to ports 8080 or 9090 already being bound. Can you confirm this? The following line can list bound ports for you:

```
lsof -iTCP -sTCP:LISTEN -n -P
```

**Comment by claudio4** [comment]
Nope. the ports are free.

**Comment by chrisvfritz** [comment]
Can you try narrowing down the issue a bit more then - for example by running specific commands in the start script one at a time and seeing where it fails? The error is rather vague unfortunately, so I don't know where to look otherwise.

**Comment by claudio4** [comment]
The problem is build:vue, webpack return [this error](http://pastebin.com/13SAadzC).

**Comment by chrisvfritz** [comment]
Ah, got it - I just pinned the Webpack dependency, which should fix this. Can you confirm?

**Comment by claudio4** [comment]
Yep, now it's work.

BTW I give you my results and my PC spec:

## Chromium 53.0.2785.116 (64-bit)

```
Vue

Fastest: 63ms
Median: 70ms
Average: 87.86ms
95th Perc.: 166ms
Slowest: 538ms
```

```
React

Fastest: 82ms
Median: 88ms
Average: 103.81ms
95th Perc.: 199ms
Slowest: 380ms
```

## Firefox 49.0.1

```
Vue

Fastest: 54ms
Median: 74ms
Average: 227.9ms
95th Perc.: 127ms
Slowest: 14782ms
```

```
React

Fastest: 191ms
Median: 210ms
Average: 234.83ms
95th Perc.: 365ms
Slowest: 723ms
```

PC specs:
- AMD FX-8350 @4.2GHz
- 16GB RAM DDR3 CL9
- ArchLinux 64-bits.

**Comment by chrisvfritz** [comment]
Thanks!
